---
tags: [reactor, rest, netty]
projects: [reactor]
---
:spring_version: current
:java_version: 1.8
:spring_boot_version: 1.0.1.RELEASE
:GraphicsMagick: http://www.graphicsmagick.org/README.html
:CuteKittensGoogle: https://www.google.com/search?q=cute+kittens&tbm=isch
:CuteKittensFlickr: https://www.flickr.com/search/?q=cute+kittens
:Component: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Component.html
:EnableAutoConfiguration: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/autoconfigure/EnableAutoConfiguration.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:Path: http://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-reactor-thumbnailer
This guide walks you through the process of creating a RESTful image thumbnailing service using Spring Boot, Reactor, and Netty.

== What you'll build

You'll build a service that thumbnails an uploaded JPEG image and stores it for serving to a web browser.


== What you'll need

include::https://raw.github.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.github.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


[[scratch]]
== Set up the project
include::https://raw.github.com/spring-guides/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.github.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]


include::https://raw.github.com/spring-guides/getting-started-macros/master/create_both_builds.adoc[]

`build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::initial/build.gradle[]
----

include::https://raw.github.com/spring-guides/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]

You'll need to download an image from {CuteKittensGoogle}[Google Images] or {CuteKittensFlickr}[Flickr] or find a JPEG image you have on local hard drive. It should be larger than 250px on the long side, as this example will thumbnail images to 250px.

[[initial]]
== Add Reactor support

The first thing you need to do is add Reactor support to your Spring Boot application. Reactor has an `@EnableRector` annotation that makes it easy to bootstrap Reactor components in a Spring `ApplicationContext`. Just add the annotation to your `@Configuration` class.

`src/main/java/org/projectreactor/examples/thumbnailer/ImageThumbnailerApp.java`
[source,java]
----
include::initial/src/main/java/hello/ImageThumbnailerApp.java
----

This adds a shared `Environment` instance to your `ApplicationContext` so that you don't have to create one. It also provides some scanning componentry that will automatically wire beans marked with the `@Consumer` annotation to a `Reactor` by attaching a `Consumer` for each method annotated with the `@Selector` annotation.

== Create the Thumbnailers

You want to delegate the actual thumbnailing of the image to different implementations depending on the environment you're running this example in. If you're on a UNIX-based system and have the excellent {GraphicsMagick}[GraphicsMagick] image manipulation software installed, then you can use that to do the thumbnailing. If not, then you can use the JDK tools for resizing an image--though the quality of those thumbnails will be drastically less than by using GraphicsMagick.

Create a `Function<Event<Path>, Path>` implementation which will be registered with the Reactor using `Reactor.receive(Selector, Function<Event<T>, V>)`. Which version you implement and register will depend on whether you have GraphicsMagick installed or not.

To implement the GraphicsMagick version, use the `gm4java` utility, which just calls the GraphicsMagick CLI to do the actual work.

`src/main/java/hello/GraphicsMagickThumbnailer.java`
[source,java]
----
include::complete/src/main/java/hello/GraphicsMagickThumbnailer.java[]
----

If you don't have GraphicsMagick installed on your machine, you can use the JDK's built-in Java2D image-handling library to do the resizing (expect a very ragged-looking result, though).

`src/main/java/hello/BufferedImageThumbnailer.java`
[source,java]
----
include::complete/src/main/java/hello/BufferedImageThumbnailer.java[]
----

== Wire up the REST API

You'll be reading images from the incoming POST requests and using a multi-threaded `Reactor` to asynchronously handle thumbnail requests.

Note: The handler expects raw binary data, not urlencoded like in an upload form. You'll need to use a command-line tool like `curl` to POST the image to the server in binary mode.

First, create a stateless helper class that will provide the appropriate `Consumer` implementations for responding to the REST API requests.

`src/main/java/hello/ImageThumbnailerRestApi.java`
[source,java]
----
include::complete/src/main/java/hello/ImageThumbnailerRestApi.java[]
----

Now wire those handlers into the server using Reactor's `Stream.filter` method to filter out requests based on URI.

`src/main/java/hello/ImageThumbnailerApp.java`
[source,java]
----
include::complete/src/main/java/hello/ImageThumbnailerApp.java[tags=restapi]
----

== Finishing up

Upload the image using a `curl` command like the following:

`curl -v -XPOST -H "Content-Type: image/jpeg" --data-binary @IMG_1984.jpg http://localhost:3000/thumbnail`

You should get a 301 response back from the server with the `Location` header pointing to the URI to pull up in your browser to see the thumbnailed image.

== Summary

Although this is about as simple a multi-component setup as you can get, this guide demonstrates:

- How to serve HTTP requests to power a REST API
- How to distribute requests to a Reactor and use it as an event bus
- How to send the response from an asynchronous task executed in a Reactor to an HTTP  client that's waiting on a result

